version: '3.9'

services:
  triton_server_modeler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        
    container_name: model_storage
    env_file:
      - .env

    # Start ssh, triton, fastapi 
    command: "bash start.sh"

    ports:
      # Triton Server Ports
      - "8100:8000"
      - "8101:8001"
      - "8102:8002"

      # Fast API port
      - "8300:8300"

      # SSH port
      - "4000:22"

    volumes:
      # Common storage volume
      - ./storage:/storage

      # Triton model repository volume
      - ./storage/model_repository:/models

    shm_size: 256m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
    stdin_open: true
    networks:
      - storage_network


networks:
  storage_network:
    driver: bridge
